services:
  accounts:
    image: swiftdocking/accounts:s4
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - swiftdocking-network
  loans:
    image: swiftdocking/loans:s4
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - swiftdocking-network
  cards:
    image: swiftdocking/cards:s4
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - swiftdocking-network
networks:
  swiftdocking-network:
    driver: bridge