spring:
  application:
    name: MySpringApp
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  h2:
    console:
      enabled: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"

server:
  port: 8080

## yaml
#springdoc:
#  swagger-ui:
#    path: /swagger-ui/index.html

build:
    version: 3.0.0

accounts:
  message: Welcome to the Accounts Microservice from Local Profile!
  contactDetails:
    name: John Doe
    email: test@test.com
  contactUs:
    -1-234-567-890
