spring:
  config:
    activate:
      on-profile: qa

build:
  version: 2.0.0

accounts:
  message: Welcome to the Accounts Microservice from QA Profile!
  contactDetails:
    name: John Doe
    email: test@test.com
  contactUs:
    -1-234-567-890